parameters:
    ezpublish.fieldType.ezimage.io_legacy.class: eZ\Publish\Core\FieldType\Image\IO\Legacy
    ezpublish.fieldType.ezimage.io_legacy.factory.class: eZ\Bundle\EzPublishLegacyBundle\FieldType\Image\IO\IOServiceFactory
    ezpublish_legacy.image_alias.cleaner.class: eZ\Publish\Core\MVC\Legacy\Image\AliasCleaner

services:
    ezpublish_legacy.image_alias.cleaner:
        class: %ezpublish_legacy.image_alias.cleaner.class%
        arguments: [@ezpublish.image_alias.imagine.alias_cleaner, @ezpublish.fieldType.ezimage.io_service]
        lazy: true
