parameters:
    ezpublish.core.io.handler.legacy.class: eZ\Publish\Core\IO\Handler\InMemory

services:
    ezpublish.core.io.handler.legacy:
        public: false
        factory_service: ezpublish.core.io.factory
        factory_method: getHandler
        arguments:
            - %ezpublish.core.io.handler.legacy.class%
            - [var_dir, storage_dir]
        calls:
            - [setLegacyKernel, @ezpublish_legacy.kernel]
