parameters:
    ezpublish_legacy.security.firewall_listener.class: eZ\Publish\Core\MVC\Legacy\Security\Firewall\LegacyListener
    ezpublish.security.auth.entry_point.legacy.class: eZ\Publish\Core\MVC\Legacy\Security\EntryPoint\LegacyEntryPoint

services:
    ezpublish_legacy.security.firewall_listener:
        class: %ezpublish_legacy.security.firewall_listener.class%
        abstract: true
        parent: ezpublish.security.firewall_listener.default

    ezpublish_legacy.security.auth.entry_point:
        class: %ezpublish.security.auth.entry_point.legacy.class%
        abstract: true
        arguments: [@router]
