parameters:
    # Below default parameters, to be defined in app/config/config.yml
    #ezpublish_legacy.enabled: false
    #ezpublish_legacy.root_dir: ~

    ezpublish_legacy.kernel.lazy_loader.class: eZ\Publish\Legacy\KernelLoader
    ezpublish_legacy.controller.class: eZ\Bundle\EzPublishLegacyBundle\Controller\LegacyKernelController
    ezpublish_legacy.router.class: eZ\Bundle\EzPublishLegacyBundle\Routing\FallbackRouter

services:
    ezpublish_legacy.kernel:
        alias: ezpublish_legacy.kernel.lazy

    ezpublish_legacy.kernel.lazy:
        class: Closure
        factory_service: ezpublish_legacy.kernel.lazy_loader
        factory_method: buildLegacyKernel
        arguments:
            - %ezpublish_legacy.root_dir%
            - %webroot_dir%

    ezpublish_legacy.kernel.lazy_loader:
        class: %ezpublish_legacy.kernel.lazy_loader.class%

    ezpublish_legacy.controller:
        class: %ezpublish_legacy.controller.class%
        arguments: [@ezpublish_legacy.kernel, @templating]

    ezpublish_legacy.router:
        class: %ezpublish_legacy.router.class%
        tags:
            - {name: router, priority: -255}
