parameters:
    # Below default parameters, to be defined in app/config/config.yml
    #ezpublish_legacy.enabled: false
    #ezpublish_legacy.root_dir: ~

    ezpublish_legacy.kernel.class: eZ\Bundle\EzPublishLegacyBundle\Services\LegacyKernel
    ezpublish_legacy.templating.bridge.class: eZ\Bundle\EzPublishLegacyBundle\Templating\Bridge

services:
    ezpublish_legacy.kernel:
        class: %ezpublish_legacy.kernel.class%
        arguments: [%ezpublish_legacy.root_dir%, %webroot_dir%]

    ezpublish_legacy.template_bridge:
        class: %ezpublish_legacy.templating.bridge.class%
        arguments: [@ezpublish_legacy.kernel]
