parameters:
    ezpublish_legacy.content_view_provider.class: eZ\Publish\Legacy\View\ContentViewProvider
    ezpublish_legacy.content_view_decorator.twig.class: eZ\Publish\Legacy\View\TwigContentViewLayoutDecorator
    ezpublish_legacy.content_view_decorator.options:
        layout: %ezpublish_legacy.view.default_layout%
        contentBlockName: %ezpublish_legacy.view.content_block_name%

services:
    ezpublish_legacy.content_view_provider:
        class: %ezpublish_legacy.content_view_provider.class%
        arguments: [@ezpublish_legacy.kernel, @ezpublish_legacy.content_view_decorator, @?logger]
        tags:
            - {name: ezpublish.content_view_provider, priority: -255}

    ezpublish_legacy.content_view_decorator.twig:
        class: %ezpublish_legacy.content_view_decorator.twig.class%
        arguments: [@twig, %ezpublish_legacy.content_view_decorator.options%]

    ezpublish_legacy.content_view_decorator:
        alias: ezpublish_legacy.content_view_decorator.twig
