language: php

# run tests on php misc php versions
php:
  - 5.4
  - 5.5
  - 5.6

# test only master (+ Pull requests)
branches:
  only:
    - master

# setup requirements for running unit tests
before_script:
  # TEMP get latests version of composer which is faster
  ##- composer self-update
  # Disable xdebug to speed things up as we don't currently generate coverge on travis
  - if [ $TRAVIS_PHP_VERSION != "hhvm" ]; then phpenv config-rm xdebug.ini ; fi
  # Setup github key to avoid api rate limit
  - ./composer_install_github_key.sh
  # Install packages using composer
  - composer install --dev --prefer-dist
  # Copy default test configuration
  - cp config.php-DEVELOPMENT config.php

# execute phpunit as the script command
script: "./bin/phpunit -d date.timezone='America/New_York' -d memory_limit=-1"

# disable mail notifications
notification:
  email: false

# reduce depth (history) of git checkout
git:
  depth: 30
